# Generated by Django 4.1.2 on 2023-02-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_room_categories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="categories",
            new_name="category",
        ),
    ]
